from types import SimpleNamespace
from typing import Never, cast
from unittest.mock import AsyncMock, Mock

import pytest
from agent_framework import WorkflowContext

from app.core.settings import Settings
from app.models import Citation, GeneratedAnswer, RetrievedDocument, WorkflowOptions
from app.models.chat import AgenticRAGState
from app.workflows.executors import AgenticRAGExecutors


def _build_document() -> RetrievedDocument:
    return RetrievedDocument(
        document_id="doc-1",
        content_id="chunk-1",
        title="Case Status Guide",
        content="Check the case dashboard to see the latest status and assigned reviewer.",
        source="kb/case-status.md",
        page_number=1,
        score=0.98,
        reranker_score=3.5,
    )


def _build_executors(*, search_results=None, generated_answer=None) -> AgenticRAGExecutors:
    query_rewriter = Mock()
    query_rewriter.generate_hyde_search_query = AsyncMock(return_value="rewritten case status query")

    search_service = Mock()
    search_service.search_async = AsyncMock(return_value=search_results or [])

    answer_generator = Mock()
    answer_generator.generate_answer = AsyncMock(return_value=generated_answer)

    return AgenticRAGExecutors(
        settings=cast(Settings, SimpleNamespace()),
        logger=Mock(),
        workflow_options=WorkflowOptions(enable_query_rewriting=True),
        search_service=search_service,
        citation_tracker=Mock(),
        query_rewriter=query_rewriter,
        answer_generator=answer_generator,
        reflection_agent=Mock(),
    )


@pytest.mark.unit
def test_agentic_rag_state_model_dump_omits_removed_search_flag() -> None:
    state = AgenticRAGState(query="What is the status of my case?")

    assert "searched_without_filters" not in state.model_dump()


@pytest.mark.unit
@pytest.mark.asyncio
async def test_search_executor_omits_removed_search_flag_from_thought_process() -> None:
    document = _build_document()
    executors = _build_executors(search_results=[document])
    state = AgenticRAGState(
        query="What is the status of my case?",
        filters={"document_type": "pdf", "product": None},
    )
    send_message = AsyncMock()
    ctx = cast(WorkflowContext[AgenticRAGState, Never], SimpleNamespace(send_message=send_message))

    await executors.search_executor(state, ctx)

    retrieve_step = state.thought_process[-1]
    assert retrieve_step["step"] == "retrieve"
    assert retrieve_step["details"]["generated_search_query"] == "rewritten case status query"
    assert retrieve_step["details"]["applied_filters"] == {"document_type": "pdf"}
    assert "searched_without_filters" not in retrieve_step["details"]
    send_message.assert_awaited_once_with(state)


@pytest.mark.unit
@pytest.mark.asyncio
async def test_answer_generator_executor_omits_removed_search_flag_from_response_details() -> None:
    document = _build_document()
    citation = Citation(
        document_id=document.document_id,
        content_id=document.content_id,
        content=document.content,
        document_title=document.title,
        page_number=document.page_number,
    )
    executors = _build_executors(
        generated_answer=GeneratedAnswer(
            answer_text="Check the case dashboard to see the latest status and assigned reviewer. [1]",
            citations=[citation],
            metadata={"document_count": 1, "cited_count": 1},
        )
    )
    state = AgenticRAGState(
        query="What is the status of my case?",
        vetted_results=[document],
        chat_history=[],
    )
    yield_output = AsyncMock()
    ctx = cast(WorkflowContext[AgenticRAGState, Never], SimpleNamespace(yield_output=yield_output))

    await executors.answer_generator_executor(state, ctx)

    response_step = state.thought_process[-1]
    assert response_step["step"] == "response"
    assert response_step["details"]["final_answer"] == state.answer
    assert response_step["details"]["citations_count"] == 1
    assert "searched_without_filters" not in response_step["details"]
    assert state.answer is not None
    assert "generated by searching across all available documents" not in state.answer
    yield_output.assert_awaited_once_with(state)
